# Generated by Django 4.1.4 on 2022-12-27 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_authentication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_authentication',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_authentication',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user_authentication',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_authentication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
