# Generated by Django 4.1.4 on 2022-12-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_authentication_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_authentication',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='user_authentication',
            name='password2',
        ),
    ]
